import Sidebar from "../components/sidebar";
import "../../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EBD Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid md:grid-cols-sidebar">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
